'use strict';

/**
 * @ngdoc function
 * @name nodejsAngularApp.controller:MainCtrl
 * @description
 * # MainCtrl
 * Controller of the nodejsAngularApp
 */
angular.module('app')
  .controller('mainctrl', ['$scope','$state',function($scope,$state){
		$scope.userInfo = {
			usename:"13180@qq.com",
			password:"131",
			autoLogin:true
		};
		var login ={
			'usename' :$scope.userInfo.usename,
			'password':$scope.userInfo.password,
			'auto'    :$scope.userInfo.autoLogin
		};
		$scope.register = function()
		{
			//alert("register:" + login);
		};
		$scope.login    = function()
		{
			//alert("login:" + login);
			$state.go("frame.views.dashboard");
		};
		var headerMenuList = [
					{
					  name:'首页',
					  href:'#'
					},
					  {
					  name:'功能',
					  href:'#'
					},
					  {
					  name:'Profile',
					  href:'#'
					},
					  {
					  name:'帮助',
					  href:'#'
					},
					  {
					  name:'设置',
					  href:'#',
					  data:[
					  {
					  	name:'我的资料',
					  	href:'#'
					  },
					  {
					  	name:'修改密码',
					  	href:'#'
					  },
					  {
					  	name:'退出',
					  	href:''
					  }
					  ]
					},
					{
						name:'修改主题',
						href:'#',
						data:[
						{
							name:'主题1',
							href:'#'
						},
						{
							name:'主题2',
							href:'#'
						},
						{
							name:'主题3',
							href:'#'
						}
						]
					}
				];
				var sideMenuList = [
					{
						item:'Dashboard',
						icon:'dashboard',
						href:'#/frame/views/dashboard'
					},
					{
						item:'Cards',
						icon:'cards',
						href:'#'
					},
					{
						item:'Charts',
						icon:'charts',
						subItems:[
						{
							item:'Flot',
							href:'#/frame/views/charts/flot'
						},
						{
							item:'Radial',
							href:'#/frame/views/charts/radial'
						},
						{
							item:'Rickshaw',
							href:'#/frame/views/charts/rickshaw'
						}
						]
					},
					{
						item:'Forms',
						icon:'forms',
						subItems:[
						{
							item:'Classic',
							href:'#/frame/views/forms/classic'
						},
						{
							item:'Validation',
							href:'#/frame/views/forms/validation'
						},
						{
							item:'Advanced',
							href:'#/frame/views/forms/advanced'
						},
						{
							item:'Material',
							href:'#/frame/views/forms/material'
						},
						{
							item:'Editors',
							href:'#/frame/views/forms/editors'
						},
						{
							item:'Upload',
							href:'#/frame/views/forms/upload'
						},
						{
							item:'Dropzone',
							href:'#/frame/views/forms/dropzone'
						},
						{
							item:'xEditable',
							href:'#/frame/views/forms/xeditable'
						}
						]
					},
					{
						item:'Tables',
						icon:'tables',
						subItems:[
						{
							item:'Classic',
							href:'#'
						},
						{
							item:'DataTable',
							href:'#'
						},
						{
							item:'ngTable',
							href:'#'
						},
						{
							item:'xEditable',
							href:'#'
						}
						]
					},
					{
						item:'Layouts',
						icon:'layouts',
						subItems:[
						{
							item:'Columns',
							href:'#'
						},
						{
							item:'Overlap',
							href:'#'
						},
						{
							item:'Boxed',
							href:'#'
						},
						{
							item:'Tabs Deep Link',
							href:'#'
						},
						{
							item:'Containers',
							href:'#'
						}
						]
					},
					{
						item:'Elements',
						icon:'elements',
						subItems:[
						{
							item:'Colors',
							href:'#'
						},
						{
							item:'Whiteframes',
							href:'#'
						},
						{
							item:'Lists',
							href:'#'
						},
						{
							item:'Bootstrapui',
							href:'#'
						},
						{
							item:'Buttons',
							href:'#'
						},
						{
							item:'Sweet-alert',
							href:'#'
						},
						{
							item:'Spinners',
							href:'#'
						},
						{
							item:'Navtree',
							href:'#'
						},
						{
							item:'Grid',
							href:'#'
						},
						{
							item:'Grid Masonry',
							href:'#'
						},
						{
							item:'Typography',
							href:'#'
						},
						{
							item:'Icons',
							href:'#'
						},
						{
							item:'Utilities',
							href:'#'
						}
						]
					},
					{
						item:'Maps',
						icon:'maps',
						subItems:[
						{
							item:'Google Maps Full',
							href:'#'
						},
						{
							item:'Google Maps',
							href:'#'
						},
						{
							item:'Vector Maps',
							href:'#'
						},
						{
							item:'Datamaps',
							href:'#'
						}
						]
					},
					{
						item:'Pages',
						icon:'pages',
						subItems:[
						{
							item:'Timeline',
							href:'#'
						},
						{
							item:'Invoice',
							href:'#'
						},
						{
							item:'Pricing',
							href:'#'
						},
						{
							item:'Contacts',
							href:'#'
						},
						{
							item:'FAQ',
							href:'#'
						},
						{
							item:'Projects',
							href:'#'
						},
						{
							item:'Blog',
							href:'#'
						},
						{
							item:'Article',
							href:'#'
						},
						{
							item:'Profile',
							href:'#'
						},
						{
							item:'Gallery',
							href:'#'
						},
						{
							item:'Wall',
							href:'#'
						},
						{
							item:'Search',
							href:'#'
						},
						{
							item:'Message Board',
							href:'#'
						}
						]
					},
					{
						item:'User',
						icon:'user',
						subItems:[
						{
							item:'Login',
							href:'#'
						},
						{
							item:'Signup',
							href:'#'
						},
						{
							item:'Lock',
							href:'#'
						},
						{
							item:'Recover',
							href:'#'
						}
						]
					},
					{
						item:'HTML5/jQuery',
						icon:'jtml',
						href:'#'
					}
				];
		$scope.headerMenuList = headerMenuList.reverse();
		$scope.sideMenuList = sideMenuList;
		sideMenuStructTransform($scope.sideMenuList);
		$scope.showsubmenu = true;
		$scope.asideclick = function(event)
		{
			//$(".submenu").each(function(key,value){
			var value = $(event.target).siblings().first();
			if($scope.lastSelected==event.target)
			{
				value.css("display") == 'block'?value.css('display','none'):value.css('display','block');
			}
			else{
				if($scope.lastSelected)
				$($scope.lastSelected).siblings().first().css('display','none');
				value.css('display','block');
				$scope.lastSelected = event.target;
			}
			//});
		};
	}]);
